CREATE TABLE concerts (
    id BIGINT PRIMARY KEY,
    artist VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    concert_year INT NOT NULL,
    total_seats INT NOT NULL CHECK (total_seats >= 0),
    cancelled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE visitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    vip BOOLEAN NOT NULL,
    wishes VARCHAR(1000)
);

CREATE TABLE ticket_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id BIGINT NOT NULL,
    concert_id BIGINT NOT NULL,
    quantity INT NOT NULL CHECK (quantity BETWEEN 1 AND 5),
    CONSTRAINT fk_ticket_visitor FOREIGN KEY (visitor_id) REFERENCES visitors(id),
    CONSTRAINT fk_ticket_concert FOREIGN KEY (concert_id) REFERENCES concerts(id)
);
